# Config file for Travis CI
language: python
python:
  - "2.7"

before_install:
# Java needed for Trimmomatic
  - "sudo apt-get install java-common"
# Use planemo to do the testing
  - "pip install planemo"
# Bootstrap Galaxy instance for tests
  - git clone https://github.com/pjbriggs/bioinf-software-install.git
  - bioinf-software-install/install_galaxy.sh galaxy-dist

script:
# Trimmomatic
  - "trimmomatic/run_planemo_tests.sh --galaxy_root galaxy-dist"
# Palfinder
  - "pal_finder/run_planemo_tests.sh --galaxy_root galaxy-dist"

