# Config file for Travis CI
language: python
python:
  - "2.7"
# Attempt to split the tests into separate
# environments
env:
  - TOOL=trimmomatic PLANEMO_OPTIONS="--no_conda_auto_install --no_conda_auto_init"
  - TOOL=pal_finder PLANEMO_OPTIONS="--no_conda_auto_install --no_conda_auto_init"
  - TOOL=weeder2 PLANEMO_OPTIONS="--no_conda_auto_install --no_conda_auto_init"
  - TOOL=rnachipintegrator PLANEMO_OPTIONS="--no_conda_auto_install --no_conda_auto_init"
  - TOOL=macs21 PLANEMO_OPTIONS="--no_conda_auto_install --no_conda_auto_init"
  - TOOL=ceas PLANEMO_OPTIONS="-no_conda_auto_install --no_conda_auto_init"

before_install:
# Update the list of available packages
  - sudo apt-get -qq update
# Java needed for Trimmomatic
  - "sudo apt-get install java-common"
# Dependencies needed for Galaxy installer
  - sudo apt-get install pwgen
  - sudo apt-get install r-base

install:
# Get the installer scripts
  - "git clone https://github.com/pjbriggs/bioinf-software-install.git"
# Install Samtools 0.1.18
  - "wget http://sourceforge.net/projects/samtools/files/samtools/0.1.18/samtools-0.1.18.tar.bz2"
  - "bioinf-software-install/install_samtools.sh samtools-0.1.18.tar.bz2 apps"
  - "export PATH=$PATH:$PWD/apps/samtools/0.1.18/"
# Bootstrap Galaxy instance for tests
  - "bioinf-software-install/install_galaxy.sh --repo https://github.com/galaxyproject/galaxy/ travis"
  - ". travis/galaxy_venv/bin/activate"
# Update setuptools before installing planemo
# See https://github.com/galaxyproject/planemo/issues/520
  - "pip install --upgrade pip setuptools"
# Install planemo to do the testing
  - "pip install planemo"

script:
# Use the Galaxy virtualenv
  - ". travis/galaxy_venv/bin/activate"
# Run tool tests
  - "tools/$TOOL/run_planemo_tests.sh --galaxy_root travis/galaxy $PLANEMO_OPTIONS"

