# Config file for Travis CI
language: python
python:
  - "2.7"

before_install:
# Java needed for Trimmomatic
  - "sudo apt-get install java-common"
# pwgen needed for Galaxy installer
  - sudo apt-get install pwgen

install:
# Bootstrap Galaxy instance for tests
  - "git clone https://github.com/pjbriggs/bioinf-software-install.git"
  - "bioinf-software-install/install_galaxy.sh travis"
  - ". travis/galaxy_venv/bin/activate"
# Install planemo to do the testing
  - "pip install planemo"

script:
# Use the Galaxy virtualenv
  - ". travis/galaxy_venv/bin/activate"
# Trimmomatic
  - "trimmomatic/run_planemo_tests.sh --galaxy_root travis/galaxy-dist"
# Palfinder
  - "pal_finder/run_planemo_tests.sh --galaxy_root travis/galaxy-dist"

